Hive:
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  initialSize: 1
  maxActive: 20
  maxPoolPreparedStatementPerConnectionSize: 20
  maxWait: 60000
  minEvictableIdleTimeMillis: 30000
  minIdle: 3
  password: bTFdydVfzW8w0
  poolPreparedStatements: true
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
#  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:hive2://172.22.222.31:10000/default
  user: liuhao8
  validationQuery: select 1